contracts/utils/Implementation.sol

use codesize instead of extcodesize

---

contracts/operators/CollectionBatchBuyOperator.sol
test/operators/CollectionBatchBuyOperator.t.sol

Addresses finding 2 relating to the ability to buy an asset already owned by the party. Additionally, accounts for possible refunds from NFT marketplaces.

Mitigation `CollectionBatchBuyOperator`

---

contracts/proposals/ListOnZoraProposal.sol

camelcase for all tokenId in `ListOnZoraProposal`

---

contracts/operators/CollectionBatchBuyOperator.sol
contracts/operators/ERC20SwapOperator.sol
contracts/operators/IOperator.sol
contracts/proposals/OperatorProposal.sol
contracts/proposals/ProposalExecutionEngine.sol
contracts/proposals/ProposalStorage.sol
test/crowdfund/CrowdfundFactory.t.sol
test/operators/CollectionBatchBuyOperator.t.sol
test/operators/ERC20SwapOperator.t.sol
test/party/PartyFactory.t.sol
test/proposals/OperatorProposal.t.sol
test/proposals/ProposalExecutionEngine.t.sol

> **Warning**
> Will need to let frontend team know about breaking ABI changes before merging

fix(`OperatorProposal`): allow disable using Operators

---

test/proposals/ListOnZoraProposalForked.t.sol
test/utils/SetupPartyHelper.sol

This PR fixes the Zora fork tests such that they actually run on a full party instance

test: Fix zora fork tests

---

contracts/renderers/PartyNFTRenderer.sol
test/party/PartyGovernanceNFT.t.sol

bug: specify rendering method in custom metadata

---

.github/workflows/ci.yml
contracts/party/PartyGovernance.sol
contracts/proposals/LibProposal.sol
test/TestUsers.sol
test/distribution/DummyTokenDistributorParty.sol
test/distribution/TokenDistributor.t.sol
test/distribution/TokenDistributorUnit.t.sol
test/party/PartyGovernance.t.sol
test/party/PartyGovernanceNFT.t.sol

feat: skip veto period when all hosts accept

---

utils/verify.ts

chore: delete random comment

---

.github/workflows/ci.yml
foundry.toml
package.json
test/crowdfund/Crowdfund.t.sol
test/crowdfund/InitialETHCrowdfund.t.sol
test/crowdfund/ReraiseETHCrowdfund.t.sol
test/party/PartyGovernanceNFT.t.sol
test/utils/FullBase64.sol
test/utils/LintJSON.sol
utils/lint-json.ts

This PR adds JSON linting to tests to ensure that the URI returned by the contracts is valid.

chore: lint json

---

deploy/Deploy.s.sol

Reverts PartyDAO/party-protocol#295

Revert "chore: set party factory in deploy"

---

contracts/renderers/PartyNFTRenderer.sol
deploy/Deploy.s.sol
deploy/LibDeployConstants.sol
test/crowdfund/InitialETHCrowdfund.t.sol
test/party/PartyGovernanceNFT.t.sol
test/utils/PartyGovernanceHelpers.t.sol

chore: immutable old token dst nft renderer

---

codecov.yml
contracts/party/PartyGovernance.sol
contracts/party/PartyGovernanceNFT.sol
contracts/proposals/ProposalExecutionEngine.sol
contracts/proposals/ProposalStorage.sol
contracts/proposals/SetGovernanceParameterProposal.sol
test/party/PartyGovernance.t.sol
test/party/PartyGovernanceUnit.t.sol
test/proposals/SetGovernanceParameterProposal.t.sol

feat: New proposal type `SetGovernanceParameterProposal`

---

contracts/party/PartyGovernance.sol
test/crowdfund/ContributionRouterIntegration.t.sol

Some tests needed to be updated with the rebase

fix dev branch

---

contracts/party/PartyGovernance.sol
contracts/party/PartyGovernanceNFT.sol
test/crowdfund/ReraiseETHCrowdfund.t.sol
test/party/PartyGovernanceNFT.t.sol
test/party/PartyGovernanceNFTUnit.sol
test/party/PartyGovernanceUnit.t.sol

Reduce party size below threshold

---

contracts/party/Party.sol
contracts/party/PartyGovernance.sol
contracts/signature-validators/OffChainSignatureValidator.sol
contracts/vendor/solmate/ERC721.sol
test/authorities/AddPartyCardsAuthority.t.sol
test/crowdfund/AtomicManualParty.t.sol
test/crowdfund/InitialETHCrowdfund.t.sol
test/party/PartyFactory.t.sol
test/party/PartyGovernanceNFT.t.sol
test/party/PartyGovernanceNFTUnit.sol

Reduce party size to enable mitigations

Reduce party size

---

contracts/crowdfund/InitialETHCrowdfund.sol

Complete the comment. C4 [191](https://github.com/code-423n4/2023-10-party-findings/issues/191)

Mitigation: 191 N03

---

contracts/party/PartyGovernance.sol

Fix typo. C4 [191](https://github.com/code-423n4/2023-10-party-findings/issues/191).

mitigation: 191 N02

---

contracts/crowdfund/InitialETHCrowdfund.sol

Update comments for clarity. C4 [191](https://github.com/code-423n4/2023-10-party-findings/issues/191).
Also addresses L-07 from [236](https://github.com/code-423n4/2023-10-party-findings/issues/236)

Mitigation: 191 L01

---

contracts/crowdfund/ETHCrowdfundBase.sol

Use safe cast to ensure no overflow. C4 [191](https://github.com/code-423n4/2023-10-party-findings/issues/191)

Mitigation: 191 L03

---

contracts/crowdfund/InitialETHCrowdfund.sol
test/crowdfund/InitialETHCrowdfund.t.sol

Standardize batch contribute functions in `InitialETHCrowdfund`. C4 [191](https://github.com/code-423n4/2023-10-party-findings/issues/191).

Mitigation: 191 R01

---

contracts/party/PartyGovernanceNFT.sol

Fix a comment. C4 [236](https://github.com/code-423n4/2023-10-party-findings/issues/236) L06.

mitigation: 236-L06 comment

---

contracts/proposals/IProposalExecutionEngine.sol
contracts/proposals/ProposalExecutionEngine.sol
test/party/PartyGovernanceUnit.t.sol
test/proposals/DummyProposalEngineImpl.sol
test/proposals/DummySimpleProposalEngineImpl.sol
test/proposals/ProposalExecutionEngine.t.sol

Mitigation for https://github.com/code-423n4/2023-10-party-findings/issues/475

fix: make `executeProposal()` payable

---

contracts/crowdfund/InitialETHCrowdfund.sol
test/GasBenchmarks.t.sol
test/crowdfund/InitialETHCrowdfund.t.sol

Mitigation for https://github.com/code-423n4/2023-10-party-findings/issues/433

doc(`InitialETHCrowdfund`): update delegate comments

---

contracts/crowdfund/Crowdfund.sol
contracts/crowdfund/InitialETHCrowdfund.sol
contracts/crowdfund/ReraiseETHCrowdfund.sol

Mitigation for https://github.com/code-423n4/2023-10-party-findings/issues/239

doc: add gatekeeper check comments

---

contracts/party/PartyGovernanceNFT.sol
test/TestUsers.sol
test/party/PartyFactory.t.sol
test/party/PartyGovernanceNFT.t.sol

Mitigation for https://github.com/code-423n4/2023-10-party-findings/issues/529

fix: require `distributionsRequireVote` to enable rage quit

---

contracts/party/PartyGovernanceNFT.sol
test/party/PartyGovernanceNFT.t.sol

Mitigations for https://github.com/code-423n4/2023-10-party-findings/issues/340

feat: emit ERC-4906 events for changes in voting power

---

contracts/crowdfund/ETHCrowdfundBase.sol
contracts/crowdfund/InitialETHCrowdfund.sol

Mitigatates C4 [306](https://github.com/code-423n4/2023-10-party-findings/issues/306) QA7.

mitigation: Check array lengths 306

---

contracts/crowdfund/AuctionCrowdfund.sol
contracts/crowdfund/AuctionCrowdfundBase.sol
contracts/crowdfund/BuyCrowdfund.sol
contracts/crowdfund/CollectionBatchBuyCrowdfund.sol
contracts/crowdfund/CollectionBuyCrowdfund.sol
contracts/crowdfund/InitialETHCrowdfund.sol
contracts/crowdfund/RollingAuctionCrowdfund.sol
contracts/party/Party.sol

chore: Update outdated comment about initializers

---

deploy/LibDeployConstants.sol
deploy/Zora.s.sol
package.json
utils/deploy.ts
utils/verify.ts

Update deploy script to enable deploying to zora
Link T-3600

chore: Deploy to zora

---

contracts/crowdfund/AtomicManualParty.sol
test/crowdfund/AtomicManualParty.t.sol

Enable setting authorities on creation in manual parties

chore: Set additional authorities on creation manual party

---

contracts/distribution/PushDistributor.sol
test/distribution/PushDistributor.t.sol

mitigations: Rooms distributor

---

contracts/crowdfund/ERC20LaunchCrowdfund.sol
utils/output-abis.ts

Add `PARTY_ADDRESS_KEY` functionality

---

deploy/LibDeployConstants.sol
utils/verify.ts

deploy: update deploy constants and verify
